Add --silent option for use with cron

diff --git a/bin/cloudflare-patchdns b/bin/cloudflare-patchdns
--- a/bin/cloudflare-patchdns
+++ b/bin/cloudflare-patchdns
@@ -2,12 +2,13 @@
 # update a cloudflare dns entry
 #
 NAME="$(basename $0)"
-OPTS=`getopt -n $NAME -o hu:t:T:i: --long help,url:,token:,type:,ip: -- "$@"`
+OPTS=`getopt -n $NAME -o hu:t:T:i:s --long help,url:,token:,type:,ip:,silent -- "$@"`
 if [ "$?" != 0 ]; then echo "Failed to parse options"; exit 1; fi
 
 CLOUDFLARE_URL_DEFAULT="https://api.cloudflare.com/client/v4"
 CLOUDFLARE_URL="$CLOUDFLARE_URL_DEFAULT"
 TYPE=
+SILENT=
 ACTION=run
 while true; do
 	case "$1" in
@@ -15,6 +16,7 @@ while true; do
 		-u| --url) CLOUDFLARE_URL="$2"; shift 2;;
 		-t| --token) CLOUDFLARE_TOKEN="$2"; shift 2;;
 		-T| --type) SEARCH_TYPE="$2"; shift 2;;
+		-s| --silent) SILENT=yes; shift;;
 		-i| --ip) IP="$2"; shift 2;;
 		--) shift; break;;
 		*) break;;
@@ -32,6 +34,8 @@ ct_help() {
 	-t|--token TOKEN : cloudflare token   (defaults to \$CLOUDFLARE_TOKEN)
 	-T|--type TYPE   : filter dns entry by type (defaults to all entries)
 	-i|--ip IP       : manually provide the IP address (defaults to public ip)
+	-s|--silent      : only output errors / messages if present
+
 	END
 }
 
@@ -102,6 +106,14 @@ ERRORS="$(echo "$RAW_PARSED" | jq .errors -)"
 SUCCESS="$(echo "$RAW_PARSED" | jq .success -)"
 MESSAGES="$(echo "$RAW_PARSED" | jq .messages -)"
 RESULT="$(echo "$RAW_PARSED" | jq .result -)"
-echo "$RESULT" | jq '' -
+if [ "$MESSAGES" != '[]' ]; then
+  echo "$MESSAGES" >&2
+fi
+if [ "$ERRORS" != '[]' ]; then
+  echo "$ERRORS" >&2
+fi
+if [ -z "$SILENT" ] || [ "$SUCCESS" != "true" ]; then
+  echo "$RESULT" | jq '' -
+fi
 rm "$TMPFILE"
 rm "$CONTENT_FILE"
